version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
  db:
      image: postgres:15.2-bullseye
      restart: always
      command: "-c fsync=off"  # baza działa szybciej, tylko dev
      env_file:
        - headlet/.env
      volumes:
        - db-data:/var/lib/postgresql/data/
      ports:
        - "14432:5432"
volumes:
  db-data:
